dependencies:
    #-<organizacion/repo@version>
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# Uncomment to use the .env file
dotenv: .env
# set a custom mnemonic for the development network
networks:
    default: development
    rinkeby:
        eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
        verify: True
    mainnet-fork-dev:
        eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
        verify: False
    development:
        verify: False
    ganache-local:
        verify: False
reports:
    exclude_contracts:
        - SafeMath
wallets:
    from_key: ${PRIVATE_KEY}
